### ISSUE TITLE
Signal Vector Magnitude - Accelerometer MPU6050

### ISSUE THREAD

**Issue by darlandc1998** [Perseus14/Pedometer#1]
Hello, I am implementing this code available on github to create a kind of pedometer for my final course project, but studying the calculation of the signal vector magnitude (SVM) better I realized that it is done as follows:

**int SVM = sqrt (pow (x, 2) + pow (y, 2) + pow (z, 2));**

But analyzing the available code here is as follows:

**int SVM = sqrt (pow (x - angle_x, 2) + pow (y - angle_y, 2) + pow (z - angle_z, 2));**

I would like to understand why the values were subtracted (previous value - current value) and only then perform the signal vector magnitude calculation.

Note: This code works perfectly, but I didn't understand why the subtraction between the values.

Thank you! Hugs!

**Comment by Perseus14** [comment]
Wow, this was written a long time ago, I barely remember this project but I will try to take a crack at it.

Let's take the example of calculating velocity of an object at say position ![formula](https://render.githubusercontent.com/render/math?math=s_1(x_1,y_1,z_1)) to position ![formula](https://render.githubusercontent.com/render/math?math=s_2(x_2,y_2,z_2)) in 1 unit of time would be 

&nbsp;&nbsp;&nbsp;&nbsp; ![formula](https://render.githubusercontent.com/render/math?math=v=s_2-s_1=((x_2-x_1),(y_2-y_1),(z_2-z_1)))

The magnitude of this value would be  
&nbsp;&nbsp;&nbsp;&nbsp; ![formula](https://render.githubusercontent.com/render/math?math=|v|=((x_1-x_2)^{2}%2B(y_1-y_2)^{2}%2B(z_1-z_2)^2)^{1/2})

Hope this analogy helps! I don't really recollect what exactly the section of code does but I believe this was the thought process behind it.

**Comment by darlandc1998** [comment]
I understand thank you!

Another thing rs, I applied this same logic to calculate the magnitude (MAG) of the acceleration according to its x, y and z axes, that is, I did the calculation as follows:

```
int MAG = sqrt(pow(acc_x_previous - acc_x_current, 2) + pow(acc_y_previous - acc_y_current, 2), pow(acc_z_previous - acc_z_current, 2));
```

Can you tell me mathematically if this is valid?

Thank you!
